### PR TITLE
fix up for-in loops

### PR DESCRIPTION
**Pull request by AprilArcus**

### CODE REVIEW

**Comment by marten-de-vries** [comment]
Thanks for the PR! It's a very nice start, but there's still a bug inside. Consider the following:

```js
for (var i in functionWithSideEffect()) {
  // ...
}
```

``functionWithSideEffect`` would be called twice in this implementation as far as I can see, while it should only be called once. This could be solved by adding a temporary variable to which the result is saved, before forming the key list. This same variable could then also be used for the later check.

**Comment by marten-de-vries** [comment]
I did just merge your first commit by the way, that one is great as-is.

**Comment by AprilArcus** [comment]
Thanks for catching that! I've amended my second commit to address it.

**Comment by marten-de-vries** [comment]
Looks great! It also shows clearly that long-term, the nested if statement refactoring can be made nicer, but for now let's aim at correctness first. :+1:

**Pull request merged**
