### PR TITLE
fix: don't hoist functions in objects

### PR DESCRIPTION
**Pull request by dariocravero**
Here's a fix for an edge case with kneden's function hoisting from functions defined as object values.

If you're using the `es2015` preset, a code like:

```
async function run() {
  var o1 = {
    a: function() { }
  };
  var o2 = {
    a: function() { }
  };
}
```

Pre kneden would be converted to:

```
async function run() {
  var o1 = {
    a: function a() { }
  };
  var o2 = {
    a: function a() { }
  };
}
```
This is because of `babel-helper-function-name`. Essentially the functions get a name. The problem is that if different objects have the same keys and those keys happen to have functions as values, their name would be the same. [That doesn't seem to matter at runtime though](https://github.com/babel/babel/pull/3474#issuecomment-211981751)... but! If you pass it through kneden, you get this:

```

function run() {
  function a() {}
  function a() {}
  var o1, o2;
  return Promise.resolve().then(function () {
    o1 = {
      a: a };
    o2 = {
      a: a };
  });
}
```

And that's the end of the game because the last definition of `a` wins and you loose one function :(.
[Here's a repo with sample code showing the issue](https://github.com/dariocravero/function-name).

I first thought this was a babel issue, see https://github.com/babel/babel/pull/3474. The way I see it, babel's output, despite seeming technically sound, feels a bit confusing for its users.

Because I don't know if the fix will make it into babel, I'm filing this PR to prevent kneden from hoisting those types of functions. :)

### CODE REVIEW

**Comment by marten-de-vries** [comment]
Thanks! Merged: dc3ff6640aef62dd1612aa94b2dd3bc9985a5389

**Comment by dariocravero** [comment]
Good stuff :)

**Comment by dariocravero** [comment]
Could you publish a patch? Thanks! :)

**Comment by marten-de-vries** [comment]
```
+ babel-plugin-async-to-promises@1.0.5
```

**Comment by dariocravero** [comment]
Thanks!

**Pull request closed without merging**
